### PR TITLE
Removed all @JvmStatic occurences.

### LINKED ISSUE #499: Android Proguard - Can't find references method 'kategory.EitherT fromEither
Hi, 

First of all thanks for the library, I'm trying to get the hand of it :)

For now, When I'm trying to compile with proguard I get this error.

```
Warning:kategory.EitherT: can't find referenced method 'kategory.EitherT fromEither(kategory.Either,kategory.Applicative)' in program class kategory.EitherT$Companion
Warning:kategory.Kleisli: can't find referenced method 'kategory.Kleisli pure(java.lang.Object,kategory.Applicative)' in program class kategory.Kleisli$Companion
Warning:kategory.Kleisli: can't find referenced method 'kategory.Kleisli ask(kategory.Applicative)' in program class kategory.Kleisli$Companion
Warning:kategory.OptionT: can't find referenced method 'kategory.OptionT pure(java.lang.Object,kategory.Applicative)' in program class kategory.OptionT$Companion
Warning:kategory.OptionT: can't find referenced method 'kategory.OptionT none(kategory.Applicative)' in program class kategory.OptionT$Companion
Warning:kategory.OptionT: can't find referenced method 'kategory.OptionT fromOption(kategory.Option,kategory.Applicative)' in program class kategory.OptionT$Companion
Warning:there were 6 unresolved references to program class members.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForProdRelease'.
> Job failed, see logs for details
```

I have only used `implementation 'io.kategory:kategory:0.3.11'` in my app.gradle with Android Studio 3.0

Any idea how I can solve this?

### PR DESCRIPTION
**Pull request by aballano**
Should fix #499

### CODE REVIEW

**Comment by pakoito** [comment]
The ones from the InstanceImplicits are required for typeclass emulation. I expect Travis to fail because of it. Let's see :P

**Comment by aballano** [comment]
@pakoito I guessed that, but yep, let's see what Travis says :D

**Comment by aballano** [comment]
@pakoito Changes done, tests green :)

Btw is there any way to remove the annotation from the instance and deriving file generator? When I try the tests fail because of the annotation processor module cannot be built, any ideas?

**Comment by pakoito** [comment]
You mean this? https://github.com/kategory/arrow/blob/master/kategory-annotations-processor/src/main/java/kategory/derive/DerivingFileGenerator.kt#L139

**Comment by aballano** [comment]
@pakoito indeed

**Comment by pakoito** [comment]
So if you remove that and do a clean build it doesn't work?

**Pull request merged**
