### PR TITLE
Adding mapLeft to Either & EitherT

### PR DESCRIPTION
**Pull request by enhan**
Simply adding the ability to map over the left value.

### CODE REVIEW

**Comment by pakoito** [comment]
Thanks for your contribution! Hope you're happy with the lib :D

For the sake of completeness, could you please add a tests and a section in the docs?

Tests:
https://github.com/kategory/arrow/blob/master/kategory-core/src/test/kotlin/kategory/data/EitherTest.kt
https://github.com/kategory/arrow/blob/master/kategory-core/src/test/kotlin/kategory/data/EitherTTest.kt

Docs:
https://github.com/kategory/arrow/blob/master/kategory-docs/docs/docs/datatypes/either/README.md
https://github.com/kategory/arrow/blob/master/kategory-docs/docs/docs/datatypes/eithert/README.md

**Comment by enhan** [comment]
@pakoito pretty happy with the lib. I added some tests & docs. Small question about the doc, how to build it and have a preview ?

**Comment by pakoito** [comment]
@enhan try this `./gradlew clean :kategory-docs:runAnk && jekyll serve --source kategory-docs/build/site`

**Comment by pakoito** [comment]
Ank fails because `EitherT(Option(3)).mapLeft({it + 1}, Option.functor())` should be `EitherT(Option(3).left()).mapLeft({it + 1}, Option.functor())`

**Comment by raulraja** [comment]
@enhan can you update your PR with latest from master so we can merge it? thanks!

**Comment by enhan** [comment]
@pakoito @raulraja Sorry for the delay, I was off for Christmas. Made some fixes to the docs, it should be ok for CI now.

**Comment by raulraja** [comment]
@enhan thanks for your contribution!

**Pull request merged**
