### PR TITLE
Update Kotlin to 1.2.10 and use the correct stdlib artifact for 1.2

### PR DESCRIPTION
**Pull request by kevinherron**

### CODE REVIEW

**Comment by pakoito** [comment]
We need @raulraja approval before merging, as we're in the middle of a large refactor. It should be okay tho :D

**Comment by raulraja** [comment]
@kevinherron can you update your PR with latest from master so we can merge it? thanks!

**Comment by kevinherron** [comment]
Updated 👍

**Comment by raulraja** [comment]
@kevinherron thanks for your contribution!

**Pull request merged**
